"""
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
    1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
"""

# Beginning from the first two terms in the Fibonacci sequence, we see that the first term, 1, is odd and the second, 2, is even.
# Necessarily, the third term is odd since odd + even = odd.
# The fourth term is similarly odd. The next term that is even is the fifth term, since the preceeding two terms are odd (odd + odd = even).
# Thus only every third term after 2 is even.
# So the even terms in the sequence are 2, 8, 34, 144, ...

phi = (1 + 5 ** .5) / 2

# psi = (1 - 5 ** .5) / 2


def direct_fibonacci(
        n: int
):
    '''
    Directly calculate the nth term in the Fibonacci sequence by truncating the golden ratio, Φ, and certain powers of it.
    Implemented using Binet's formula 

    :param n: Description
    :type n: int
    '''
    return ((phi) ** (n) - (-phi) ** (-n)
            ) // (2 * phi - 1)


def expontiate(x: , n):
    if n == 0 and x != 1:
        return 1  # Valid unless


def iterative_fibonacci(
        n: int
):
    '''
    Iteratively generate the nth term in the Fibonacci sequence.

    :param n: Description
    :type n: int
    '''

    if n == 0:
        return 0
    elif n == 1:
        return 1
    else:
        a, b = 0, 1
        for _ in range(n):
            a, b = b, a + b
        return b


print(
    sum(
        [
            direct_fibonacci(i)
            for i in range(0, 34, 3)
        ]
    )
)
