"""
<p>Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:</p>
<p class="center">1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...</p>
<p>By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.</p>
"""

phi = (1 + 5 ** .5) / 2

# psi = (1 - 5 ** .5) / 2

def fibonacci( n: int ) :
    return int( (phi ** (n) - (- phi) ** (-n)) // (2 * phi - 1) )

print( sum( [ fibonacci( i )
              for i in range( 0, 34, 3 )
              ] ) )
